---
deployment:
  tasks:
    - export DEPLOYPATH=/home/ibijxaea/kindredpathway
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R img $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp -R lib $DEPLOYPATH
    - /bin/cp -R animate $DEPLOYPATH
    - /bin/cp -R counterup $DEPLOYPATH
    - /bin/cp -R easing $DEPLOYPATH
    - /bin/cp -R owkarousel $DEPLOYPATH
    - /bin/cp -R tempusdominus $DEPLOYPATH
    - /bin/cp -R waypoints $DEPLOYPATH
    - /bin/cp -R wow $DEPLOYPATH
    - /bin/cp *.html $DEPLOYPATH
    - /bin/cp *.ico $DEPLOYPATH
    - /bin/cp *.png $DEPLOYPATH
